name: "Check kicad files"
description: "Run you ERC and DRC tests for KiCad."
branding:
  icon: "check-circle"
  color: "yellow"

inputs:
  file:
    description: "The location to the schematic or PCB file."
    required: true
  type:
    description: >
      Check type, choose one of the following:
      - erc
      - drc
    required: true

runs:
  using: "composite"
  steps:
    - id: check-files
      name: "Check files."
      run: ${{ github.action_path }}/check-files.sh --type "${{ inputs.type }}" "${{ inputs.file }}"
      shell: bash
