name: Tests

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  check-export:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kicad-version: ["8.0"]
        test-name: ["erc-failure", "erc-success", "drc-failure", "drc-success"]
        include:
          - test-name: erc-failure
            type: erc
            file: tests/kicad-project-failure/kicad-project.kicad_sch
            result: failure
          - test-name: erc-success
            type: erc
            file: tests/kicad-project-success/kicad-project.kicad_sch
            result: success
          - test-name: drc-failure
            type: drc
            file: tests/kicad-project-failure/kicad-project.kicad_pcb
            result: failure
          - test-name: drc-success
            type: drc
            file: tests/kicad-project-success/kicad-project.kicad_pcb
            result: success
    steps:
      - uses: actions/checkout@v4
      - uses: actions-for-kicad/setup-kicad@main
        with:
          version: ${{ matrix.kicad-version }}
      - name: Set KiCad Environment Paths
        run: |
          echo "KICAD8_SYMBOL_DIR=/usr/share/kicad/symbols" >> $GITHUB_ENV
          echo "KICAD8_TEMPLATE_DIR=/usr/share/kicad/template" >> $GITHUB_ENV
          echo "KICAD8_FOOTPRINT_DIR=/usr/share/kicad/footprints" >> $GITHUB_ENV
          echo "KICAD8_3DMODEL_DIR=/usr/share/kicad/3dmodels" >> $GITHUB_ENV
      - name: Check file
        id: check_file
        uses: ./
        with:
          file: ${{ matrix.file }}
          type: ${{ matrix.type }}
        continue-on-error: true
      - name: Verify Check File Step Result
        run: |
          if [[ "${{ matrix.result }}" == "failure" && "${{ steps.check_file.outcome }}" != "failure" ]]; then
            echo "Expected failure, but step succeeded!"
            exit 1
          fi
          if [[ "${{ matrix.result }}" == "success" && "${{ steps.check_file.outcome }}" == "failure" ]]; then
            echo "Expected success, but step failed!"
            exit 1
          fi
        shell: bash
